
//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Mon Jan 30 16:13:52 PST 2023
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SHORT = 4;
  public static final int IDENTIFIER = 32;
  public static final int ANDEQ = 71;
  public static final int GT = 40;
  public static final int NOTEQ = 44;
  public static final int PLUSEQ = 64;
  public static final int RBRACK = 84;
  public static final int COMMA = 75;
  public static final int RBRACE = 80;
  public static final int DOUBLE_LITERAL = 31;
  public static final int RPAREN = 82;
  public static final int LBRACK = 83;
  public static final int LT = 39;
  public static final int ANDAND = 45;
  public static final int OROR = 46;
  public static final int DOUBLE = 8;
  public static final int LBRACE = 79;
  public static final int LPAREN = 81;
  public static final int RRSHIFT = 61;
  public static final int XOREQ = 67;
  public static final int INTEGER_LITERAL = 33;
  public static final int NOT = 55;
  public static final int FINAL = 28;
  public static final int FLOAT = 7;
  public static final int COMP = 54;
  public static final int EQ = 38;
  public static final int MOD = 53;
  public static final int BOOLEAN_LITERAL = 29;
  public static final int CLASS = 12;
  public static final int SUPER = 20;
  public static final int LONG = 6;
  public static final int PLUS = 49;
  public static final int LONG_LITERAL = 34;
  public static final int WHILE = 16;
  public static final int EXTENDS = 22;
  public static final int CHAR = 3;
  public static final int BOOLEAN = 9;
  public static final int DO = 17;
  public static final int FOR = 18;
  public static final int RSHIFTEQ = 69;
  public static final int VOID = 23;
  public static final int DIV = 52;
  public static final int PUBLIC = 25;
  public static final int RETURN = 24;
  public static final int MULT = 51;
  public static final int ELSE = 15;
  public static final int BREAK = 11;
  public static final int GTEQ = 42;
  public static final int DOT = 76;
  public static final int INT = 5;
  public static final int NULL_LITERAL = 35;
  public static final int STRING_LITERAL = 36;
  public static final int EQEQ = 43;
  public static final int SEMICOLON = 73;
  public static final int EOF = 0;
  public static final int THIS = 21;
  public static final int MULTEQ = 62;
  public static final int IMPORT = 78;
  public static final int MINUS = 50;
  public static final int FLOAT_LITERAL = 30;
  public static final int LTEQ = 41;
  public static final int OR = 58;
  public static final int error = 1;
  public static final int DIVEQ = 63;
  public static final int LSHIFTEQ = 68;
  public static final int CONTINUE = 13;
  public static final int INSTANCEOF = 77;
  public static final int IF = 14;
  public static final int MODEQ = 66;
  public static final int MINUSMINUS = 48;
  public static final int COLON = 74;
  public static final int CHARACTER_LITERAL = 37;
  public static final int OREQ = 72;
  public static final int PLUSPLUS = 47;
  public static final int NEW = 19;
  public static final int RSHIFT = 60;
  public static final int STRING = 10;
  public static final int BYTE = 2;
  public static final int AND = 56;
  public static final int PRIVATE = 26;
  public static final int STATIC = 27;
  public static final int LSHIFT = 59;
  public static final int XOR = 57;
  public static final int RRSHIFTEQ = 70;
  public static final int MINUSEQ = 65;
}

